/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arrayopt_qap_GraspPathRelinking */

#ifndef _Included_arrayopt_qap_GraspPathRelinking
#define _Included_arrayopt_qap_GraspPathRelinking
#ifdef __cplusplus
extern "C" {
#endif
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_RUNS
#define arrayopt_qap_GraspPathRelinking_DEFAULT_RUNS 1L
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_MAX_ITERACTIONS
#define arrayopt_qap_GraspPathRelinking_DEFAULT_MAX_ITERACTIONS 32L
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_ALPHA
#define arrayopt_qap_GraspPathRelinking_DEFAULT_ALPHA 0.1f
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_BETA
#define arrayopt_qap_GraspPathRelinking_DEFAULT_BETA 0.5f
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_ELITE_SIZE
#define arrayopt_qap_GraspPathRelinking_DEFAULT_ELITE_SIZE 10L
#undef arrayopt_qap_GraspPathRelinking_DEFAULT_SEED
#define arrayopt_qap_GraspPathRelinking_DEFAULT_SEED 270001L
/*
 * Class:     arrayopt_qap_GraspPathRelinking
 * Method:    qap_grasppr
 * Signature: (I[I[I[IFFIIIII[I)J
 */
JNIEXPORT jlong JNICALL Java_arrayopt_qap_GraspPathRelinking_qap_1grasppr
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jfloat, jfloat, jint, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
